### ISSUE TITLE
Chat/emotes are not shown, only livestream

### ISSUE THREAD

**Issue by andrewlvovsky** [seandoerr/Kappa-Cloud#2]
<img width="1440" alt="screen shot 2017-10-22 at 3 02 16 pm" src="https://user-images.githubusercontent.com/20800975/31866810-04d161ac-b73a-11e7-9b03-c02d7665dab4.png">

**Comment by seandoerr** [comment]
Are you sure you are connected to a twitch stream? In your connect.js file (which an example will be pushed soon), there should be a line of code that starts with "channels", inside the brackets you can  say "#twitch" for example and it will connect you to the twitch channel chat.

**Comment by seandoerr** [comment]
Added example connect file

**Comment by andrewlvovsky** [comment]
So the chat and emotes work now, but when I switch to a channel other than twitch, the stream still shows as the main twitch channel. The emotes and chat however are all through the new stream I put into the connect file
